### PR TITLE
Support repositories groups and aliases

### PR DESCRIPTION
**Pull request by andreiled**

### CODE REVIEW

**Comment by andreiled** [comment]
@naddeoa, I'm drafting support for configuring repositories groups.
My intention is to preserve back compatibility with currently available configuration options, though I didn't yet have the time to test that. For now I do know that the part that I need works as expected.

Here's an example of how I'm planning to configure it for my use:
```
module.exports = {
    'groups': [
        {
            'name': 'group1',
            'repositories': [
                { alias: 'First', path: 'D:/GIT/FirstRepo' },
                { alias: 'Second', path: 'D:/GIT/SecondRepo' }
            ]
        },
        {
            'name': 'group2',
            'repositories': [
                { alias: 'Third', path: 'D:/GIT/ThirdRepo' }
            ]
        }
    ]
}
```

I'm planning to later submit a Pull Request to merge this to your repository once I feel comfortable with how this turns out,so if you could let me know if I'm moving in some totally wrong direction that doesn't align with your vision for the tool, that would be great.

**Comment by naddeoa** [comment]
Hey!

Thanks for the PR. I won't have time to look at the code until the weekend but I do have a few questions to hold me over until then. First I should say that the current implementation is sort of arbitrary. I organize my projects currently in the form `root/src/project1`, `root/src/project2`, etc. I added the configuration because I thought that my project structure was pretty specific behavior that other people don't share, but I didn't know what other people were doing.

Can you go more into how you set stuff up? I'd like to understand the use case before trying to judge the code. What purpose would alias serve, for example?

**Comment by andreiled** [comment]
Hi,

Couple notes about my projects structure:
1. I keep my personal projects in one directory.
1. I have another directory with a number of company projects (about 10) depending on each other.
These projects are further separated into 3 groups.
1. Finally, I have several company projects not related to the previous group.

I mainly plan on using the tool for the second group of projects and am going to set up `.gitbulkconfig` in the directory that contains them all.
From there I want to be able to perform an operation in bulk for either:
* all of them,
* one or two groups,
* or specific repositories.

Furthermore, I need aliases for two things:
1. Repositories names are rather long and I don't want to type their whole names in, using aliases I can type in short names
2. I want to be able to share instructions for doing standard operations (e.g. merge, rebase) with other team members who may have slightly different structure of projects and local repositories names.

**Comment by naddeoa** [comment]
I like the idea of groups. I could probably use something like that as well. Do you think you could show me a little ascii tree of some directory structures that you have, and maybe some sample commands that you would imagine using on those directories?

Sorry if I'm making you do a bunch of stuff. This would complicate the current design and I want to make sure I understand it before doing anything.

**Comment by andreiled** [comment]
I can't really show my actual directories structure since that's confidential (proprietary and all that).
So here's an abstract example:
```
GIT
|__HugeProject
   |__ModuleA1
   |__ModuleA2
   |__ModuleA3
   |__ModuleB1
   |__ModuleB2
   |__.gitbulkconfig
```

The idea behind splitting repositories into groups A and B is that code in the first group is written and maintained by one team while another team works with the second group. But major releases cycles are the same across all of them, so merges need to be done across all of the repositories.

So let's say we need to merge changes from a release branch to the development branch:
`git bulk merge --from upstream/release/2.1 --to upstream/development --message "Merge from release 2.1 to development"`
_Note_: it doesn't look like merge command is there, so this is just a conjecture on how I would implement it
Modules in the second group can also hare minor releases in between, so we need to be able to merge just them as well:
`git bulk merge :b --from upstream/release/2.1.1 --to upstream/development --message "Merge from release 2.1.1 to development"`
Or let's say there's a need to merge just one of them:
`git bulk merge :a:1 --from upstream/feature/foo --to development --message "Pull feature foo into development"`

Also, let's say we want to see what changes we have sitting in a minor release branch that haven't been integrated into the development branch:
`git bulk log :b upstream/development..upstream/release/2.1.2`

P.S.: all command examples assume that current directory is `HugeProject`

**Comment by naddeoa** [comment]
Thanks, that helps. So here, `:a` would be group a and `:a:1` would be `:group:alias`, correct?

Assuming that's true, I have a few thoughts to simplify things. 

* It looks like we can enforce a constrain on alias uniqueness so that `:a:1` would be redundant. After all, the aliases are just going to be strings people pick in the config,
* I would like to invert the grouping in the config file if possible, keeping it repository oriented instead of group oriented. That might mean a little duplication in the config because people will have to repeat some `group: "groupName"` in a few of the repository fieflds. Something like the following. I would still want to be able to specify a path to a dir containing a bunch of repos for people that don't need to get fancy. Maybe we just overload the repositories field for that?
```
module.exports = {
    repositories: [
        {...},
        {...}
   ]
}
```

* To keep the CLI simple, perhaps we can just have a repeatable `--target` switch that accepts either group names or aliases. Something like `git bulk log --target alias1 --target group2 --target group3`. That implies that group names can't be aliases, but I'm not sure we need that feature.

Would those things still allow you to do what you want?

**Comment by andreiled** [comment]
Sorry for the delay - I just recently got back from a vacation.

> `:a` would be group a and `:a:1` would be `:group:alias`

Yes, that's right.
Also `::2` would point to a repository with alias `2` that is not in any of the groups.

The rationale behind the way I went about specifying a repository in CLI was to be able to clearly see what is the target just by looking at the command line regardless of the actual repositories configuration. 
If we go with your suggestion, the same command line may in theory be evaluated differently depending on the actual repositories configuration, which doesn't really sit right with me being a purist. But I'm willing to forego it under the assumption that people will be giving meaningful names to groups and aliases that ever would intersect.

> I would like to invert the grouping in the config file if possible

Yeah, I think I could do that

> I would still want to be able to specify a path to a dir containing a bunch of repos

That should still work with current code, at least that is my intention. But I didn't actually test it, and while we are on the subject: are there any tests for this functionality?

> To keep the CLI simple, perhaps we can just have a repeatable `--target`

I actually think that it will require me to do more invasive code changes that I already did. So I would prefer to just extend existing logic working with repositories names as free CLI parameters.

**Comment by andreiled** [comment]
Hi @naddeoa,

I went ahead and significantly simplified the approach.

Here is a `.gitbulkconfig` sample:
```
module.exports = {
    'repositories': [
        '/GIT/HugeProject/Foo',
        { 'name': 'A1', path: '/GIT/HugeProject/A1', 'group': 'A' },
        { 'name': 'A2', path: '/GIT/HugeProject/A2', 'group': 'A' },
        { 'name': 'A3', path: '/GIT/HugeProject/A3', 'group': 'A' },
        { 'name': 'B1', path: '/GIT/HugeProject/B1', 'group': 'B' },
        { 'name': 'B2', path: '/GIT/HugeProject/B2', 'group': 'B' }
    ]
}
```
along with some command lines samples:
* `git bulk log A` - show log for all repositories in group A
* `git bulk log A2` - show log for the repository A2
* `git bulk log Foo` - show log for the repository Foo

**Comment by naddeoa** [comment]
Nice! That a looks a lot simpler already. I'll have time to check it out on Saturday. How did you plan to specify multiple repos on the command line? I was imagining a `--target` or a `-t` switch that people use, similar to the sed command. sed lets you specify a single arg without any switches, but  requires switches for multiple args.

**Comment by andreiled** [comment]
> How did you plan to specify multiple repos on the command line?

For now I'm keeping it as it already works: `git bulk log A3 B1`

Yesterday it did occur to me that we may need to change it later on (introduce the `-t` and `--target` options) in order to let users specify additional arguments to be passed into the underlying git invocation.
But let's do that in a separate Pull Request (_divide and conquer_ approach).

**Comment by naddeoa** [comment]
Nice, I just tried it out. Looks like it works well. I actually like it a lot. What was your plan from here? Merge it into your master and have me merge it into back into gitbulk master? 

Also, I totally forgot that the repo names already worked in that way. I'm ok with keeping it like that.

**Comment by andreiled** [comment]
Sounds awesome.
The plan was for this PR to serve as kind of a preview. I'm going to merge it then and create a PR to your master repository.
I'm however thinking about updating documentation before that (e.g. adding configuration samples, etc.). How does that sound?

**Comment by naddeoa** [comment]
Yeah that would be much appreciated. I use that demo folder for running
manual testing so it would be helpful if you updated the .gitbulkconfig in
there to use names and groups.

Thanks again. BTW, how did you find git bulk?

**Comment by andreiled** [comment]
> how did you find git bulk?

Googled 'git bulk operations' :)

**Comment by andreiled** [comment]
> I use that demo folder for running manual testing

Hm, all _repositories_ in there are empty so `git bulk` just ignores them. Am I missing something there?
So far I just added [new _Configuration_ section in the `README`](https://github.com/andreiled/git-bulk/blob/feature/repo_groups/README.md#configuration).

**Comment by naddeoa** [comment]
If you clone the repo with `git clone --recursive` they will be full. They
are git submodules.

**Comment by andreiled** [comment]
Got it, thanks!

I updated `demo/.gitbulkconfig` and tested it with following results:
```
$ git bulk status -a
git-js [HEAD ➜ ]
vim-visual-page-percent [HEAD ➜ ]
onion-oled-js [HEAD ➜ ]
onion-oled [HEAD ➜ ]

$ git bulk status -a js
git-js [HEAD ➜ ]
onion-oled [HEAD ➜ ]

$ git bulk status -a onion-oled
onion-oled [HEAD ➜ ]
```

P.S.: should I bump the version with this change as well?

**Comment by naddeoa** [comment]
I'll take care of that part. After you do the pull request I'll test it out and then bump it for an npm release.

**Pull request merged**
